- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequasites for Docker
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: "{{docker_gpg_key_url}}"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt sources
  copy:
    content: "{{docker_repo_template}}"
    dest: /etc/apt/sources.list.d/docker.list

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes
  
- name: Install docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present